id: pt-BR
label: PortuguÃªs (Brasil)
translators:
  [
    "the-physicist",
    "thiagoloal",
    "willmustafa",
    "andreseichi",
    "HakaCode",
    "romulo1984",
    "rodrigoant",
    "vilaboim"
  ]
